version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sjhlagdkkfsngj
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
